apiVersion: v1
kind: Service
metadata:
  name: mayank-app-service
spec:
  selector:
    app: mayank-app
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30500
