apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayank-app
  labels: 
    app: mayank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mayank-app
  template:
    metadata:
      labels:
        app: mayank-app
    spec:
      containers:
      - name: mayank-app
        image: mayank-app:1.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      - name: reverse-proxy
        image: reverse-proxy-nginx:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
