apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: appHPA.com
 namespace: assign
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: mayank-app
 minReplicas: 1
 maxReplicas: 5
 targetCPUUtilizationPercentage: 85
